### ISSUE TITLE
Android issue

### ISSUE THREAD

**Issue by mishra-tapas** [WICG/speech-api#90] opened 2021-02-01 08:27 UTC
While using the api in Android, after the first few words, the api is detecting random words not even close to what was spoken: however in windows/Linux, the api seems to work just fine. Is there a way around to make it work on Android?
@marcoscaceres

**Comment by foolip** [comment] 2021-02-02 11:39
Closing this as a dupe of https://github.com/WICG/speech-api/issues/89 since it's the same issue text. I'll reply there.

**Closed by foolip** 2021-02-02 11:39 UTC
